services:
  processor:
    container_name: processor
    build:
      context: .
      dockerfile: ./processor/processor.Dockerfile
      target: processor
    command: bash /start-up.sh
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_PORT: 5432
    volumes:
      - ./processor/processor:/processor
      - file_repository:/tmp/html
    depends_on:
      - broker
      - database
    ports:
      - 8000:8000
  
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - 5432:5432
  
  broker:
    container_name: broker
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=RABBITMQ_DEFAULT_PASS
    ports:
      - 8080:15672
      - 5672:5672

  collector:
    command: bash /start-up.sh
    container_name: collector
    build:
      context: .
      dockerfile: ./collector/collector.Dockerfile
      target: collector
    environment:
      - ENV=development
    volumes:
      - ./collector/collector:/collector
      - file_repository:/tmp/html
    ports:
      - 8003:8003
    depends_on:
      - broker
      - sentinel
      - dispatcher
      - processor

  dispatcher:
    tty: true
    command: bash /start-up.sh
    container_name: dispatcher
    build:
      context: .
      dockerfile: ./dispatcher/dispatcher.Dockerfile
      target: dispatcher
    environment:
      - ENV=development
      - RABBITMQ_DEFAULT_USER=RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=RABBITMQ_DEFAULT_PASS
    volumes:
      - ./dispatcher/dispatcher:/dispatcher
      - file_repository:/tmp/html
    ports:
      - 8002:8002
    depends_on:
      - broker
  
  sentinel:
    command: bash /start-up.sh
    container_name: sentinel
    build:
      context: .
      dockerfile: ./collector/collector.Dockerfile
      target: sentinel
    volumes:
      - file_repository:/tmp/html
      - ./scripts/:/app
    depends_on:
      - broker

volumes:
  postgres_data:
  file_repository:
  