services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: bash /start-up.sh
    working_dir: /app
    environment:
      POSTGRES_HOST: database
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_PORT: 5432
    depends_on:
      - database
    ports:
      - 8000:8000
  
  database:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
    ports:
      - 5432:5432
  
  broker:
    container_name: broker
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=RABBITMQ_DEFAULT_PASS
    ports:
      - 8080:15672

volumes:
  postgres_data:
